#eureka.client.serviceUrl.defaultZoneeureka:
server:
    port: 2222

eureka:
  client:
    serviceUrl:
      defaultZone​: http://localhost:8761/eureka/


spring:
  application:
    name: client-service